name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest

      - name: Install Playwright Browsers
        run: |
          playwright install

      - name: Run Playwright Script
        run: |
          pytest tests/prac.py

      - name: Upload Traces (if failed)
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: test-results/
